### ISSUE TITLE
20% of tests fail 

### ISSUE THREAD

**Issue by thedarkjester** [carnisman/blockchain-developer-bootcamp-final-project#1]
I am in the process of reviewing your project and noticed on a clean build and test run when connecting to ganache I get 8/40 tests giving errors.

some samples:
```
32 passing (19s)
  8 failing

  1) Contract: PapaPay
       Use cases
         Course creation tests
           Should add a course with its parameters:
     TypeError: Cannot read property 'call' of undefined
      at Context.<anonymous> (test/PapaPay.test.js:198:51)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  2) Contract: PapaPay
       Use cases
         Course approval tests
           should allow the student to approve a course and update balance accordingly:
     TypeError: Cannot read property 'call' of undefined
      at Context.<anonymous> (test/PapaPay.test.js:283:51)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  3) Contract: PapaPay
       Use cases
         Lesson attendance tests
           should allow the student to attend a lesson and update student attendance counter:
     TypeError: Cannot read property 'call' of undefined
      at Context.<anonymous> (test/PapaPay.test.js:339:51)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  4) Contract: PapaPay
       Use cases
         Lesson init tests
           should allow the tutor to init a lessons and update tutor init counter:
     TypeError: Cannot read property 'call' of undefined
      at Context.<anonymous> (test/PapaPay.test.js:394:51)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      ```

**Comment by carnisman** [comment]
Hi! Sorry for the delay, I was a little incapacitated due to COVID :( but now back on track.

The undefined call is due to not uncommenting lines 293 to 310 (fetchCourse function) of the PapaPay.sol contract as per documentation (Avalilable in the root folder of the repository).

Under "Contract deployment and testing", the third step states _"To test the contract, edit **./contracts/PapaPay.sol**, uncomment lines 293 to 310 (fetchCourse function), save changes, and from project´s root directory run **truffle migrate --network development --reset** and then run **truffle test**"_

After testing and prior to final deployment to a live net, comment back those lines.

Maybe it´s no so clear because of my english, if so I apologize!

**Comment by thedarkjester** [comment]
thanks - you can close this issue.
